ARG TF_TAG
FROM tensorflow/tensorflow${TF_TAG}

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    mkdir -p /opt && \
    git clone https://github.com/dakoner/models-1.git --single-branch /opt/tensorflow_models
